export const skillDescriptions = {
  "HTML - Semantic & accessible": "Writing semantic, accessible HTML following modern web standards.",
  "Responsive Web Design": "Creating responsive interfaces that work across devices and screen sizes.",
  "Teamwork": "Collaborating effectively with developers, designers, and product teams.",
  "Markdown": "Creating clear technical documentation using Markdown.",
  "Immutability": "Writing predictable and maintainable code by avoiding unwanted mutations.",
  "CSS BEM Convention": "Structuring scalable CSS using the Block Element Modifier methodology.",
  "CSS Grid": "Building advanced responsive layouts with CSS Grid.",
  "CSS Flexbox": "Creating flexible layouts using Flexbox.",
  "CSS Animations & Keyframes": "Creating smooth user interface animations with CSS.",
  "JavaScript ES6+": "Building modern applications using advanced JavaScript features.",
  "Promises & Async/Await": "Managing asynchronous operations effectively in JavaScript.",
  "React.js": "Building modern component-based user interfaces with React.",
  "React Hooks": "Managing state, effects, and reusable logic with React Hooks.",
  "React Router": "Implementing client-side navigation in React applications.",
  "React Context API": "Sharing application state across React components.",
  "Redux Toolkit": "Managing complex application state using Redux Toolkit.",
  "TanStack React Query": "Fetching, caching, synchronizing, and managing server state efficiently.",
  "React Suspense": "Handling asynchronous rendering and loading states in React.",
  "React Testing": "Writing automated tests to ensure React application reliability.",
  "Styled-Components": "Creating component-based styling using CSS-in-JS.",
  "CSS-in-JS": "Managing styles inside JavaScript-based component architectures.",
  "Tailwind CSS": "Building modern user interfaces efficiently with utility-first CSS.",
  "TypeScript": "Writing safer and more maintainable applications with static typing.",
  "Advanced TypeScript": "Using advanced types, generics, and patterns for scalable applications.",
  "Working with APIs (fetch, axios, REST)": "Integrating frontend applications with backend APIs.",
  "Error Handling": "Implementing reliable error handling strategies in applications.",
  "Git": "Managing source code versions and collaboration workflows using Git.",
  "GitHub Pull Requests & Code Review": "Collaborating with teams through pull requests, reviews, and quality-focused development workflows.",
  "GitHub Team Collaboration": "Working effectively with distributed teams using GitHub collaboration tools.",
  "NPM": "Managing JavaScript dependencies and project packages with NPM.",
  "Trello": "Organizing development tasks and project workflows using Trello.",
  "Figma": "Creating and understanding UI designs and prototypes using Figma.",
  "Scrum": "Working effectively in agile development teams using Scrum methodology.",
  "Next.js App Router": "Building modern full-stack applications using the Next.js App Router architecture.",
  "Next.js Server Components": "Creating efficient React applications using server-side rendering capabilities and React Server Components.",
  "Next.js Server Actions": "Implementing secure server-side mutations and backend logic using Next.js Server Actions.",
  "Next.js Rendering Strategies (SSR, SSG, ISR)": "Optimizing application performance and SEO using Next.js rendering strategies.",
  "Next.js API Routes": "Creating backend endpoints and server functionality inside Next.js applications.",
  "Vercel Deployment": "Deploying and managing production applications using Vercel.",
  "CI/CD Pipelines": "Automating testing, builds, and deployments using continuous integration and delivery workflows.",
  "Supabase": "Using Supabase as a backend platform including database, authentication, storage, and APIs.",
  "Supabase Authentication": "Implementing secure user authentication and session management with Supabase Auth.",
  "PostgreSQL": "Designing and managing relational databases using PostgreSQL.",
  "Database Design": "Creating scalable database structures, relationships, and data models.",
  "Row Level Security (RLS)": "Protecting application data with PostgreSQL Row Level Security policies.",
  "Authentication & Authorization": "Designing secure authentication flows and permission systems.",
  "JWT Authentication": "Implementing token-based authentication using JWT.",
  "OAuth2 Integration": "Adding secure third-party authentication providers using OAuth2.",
  "SaaS Architecture": "Designing scalable SaaS applications with production-ready architecture patterns.",
  "Production Application Architecture": "Creating maintainable systems with clear architecture decisions and engineering principles.",
  "API Design": "Designing reliable and maintainable APIs for modern applications.",
  "Cloud Application Development": "Building and deploying applications using modern cloud platforms.",
  "OpenAI API Integration": "Integrating AI models, chat systems, embeddings, and intelligent features into applications.",
  "AI Application Development": "Building AI-powered products and SaaS applications using modern AI technologies.",
  "AI Agents & AI Workflows": "Creating AI-powered workflows and agent systems that automate complex tasks.",
  "Prompt Engineering": "Designing effective prompts to achieve reliable and consistent AI results.",
  "AI-Directed Engineering": "Using AI as an engineering partner for architecture decisions, coding, debugging, and improving development workflows.",
  "AI-Native Software Development": "Building software with AI integrated throughout the engineering lifecycle."
};

export const skillsets = [
  "HTML - Semantic & accessible",
  "Responsive Web Design",
  "JavaScript ES6+",
  "Promises & Async/Await",
  "React.js",
  "React Hooks",
  "React Router",
  "React Context API",
  "Redux Toolkit",
  "TanStack React Query",
  "React Testing",
  "React Suspense",
  "TypeScript",
  "Styled-Components",
  "CSS-in-JS",
  "Tailwind CSS",
  "CSS Grid",
  "CSS Flexbox",
  "Working with APIs (fetch, axios, REST)",
  "Error Handling",
  "Git",
  "GitHub Pull Requests & Code Review",
  "GitHub Team Collaboration",
  "NPM",
  "Figma",
  "Scrum",
  "Next.js App Router",
  "Next.js Server Components",
  "Next.js Server Actions",
  "Next.js Rendering Strategies (SSR, SSG, ISR)",
  "Vercel Deployment",
  "CI/CD Pipelines",
  "Supabase",
  "Supabase Authentication",
  "PostgreSQL",
  "Database Design",
  "Row Level Security (RLS)",
  "Authentication & Authorization",
  "JWT Authentication",
  "OAuth2 Integration",
  "SaaS Architecture",
  "Production Application Architecture",
  "OpenAI API Integration",
  "AI Application Development",
  "AI Agents & AI Workflows",
  "Prompt Engineering",
  "AI-Directed Engineering"
];

export const toLearn = [
  "React Testing",
  "Artificial Intelligence (AI)",
  "Advanced TypeScript",
  "AI-Native Software Engineering"
];

export const toLearnDescriptions = {
  "React Testing": "Learn to write reliable automated tests for React components and applications using modern testing practices, improving code quality and maintainability.",
  "Artificial Intelligence (AI)": "Explore AI fundamentals, large language models, AI integrations, agents, and how to build intelligent features into modern SaaS applications.",
  "Advanced TypeScript": "Develop advanced TypeScript skills including type safety, generics, utility types, and scalable application architecture.",
  "AI-Native Software Engineering": "Learn how to use AI as an engineering partner for architecture decisions, development workflows, code reviews, and building production-ready applications."
};
