export const skillDescriptions = {
  "HTML - Semántico y accesible": "Creación de HTML semántico y accesible siguiendo estándares modernos.",
  "Diseño Web Responsivo": "Creación de interfaces adaptables a diferentes dispositivos y tamaños de pantalla.",
  "Trabajo en equipo": "Colaboración efectiva con desarrolladores, diseñadores y equipos de producto.",
  "Markdown": "Creación de documentación técnica utilizando Markdown.",
  "Inmutabilidad (Immutability)": "Escritura de código predecible evitando mutaciones no deseadas.",
  "Convención BEM en CSS": "Organización de CSS escalable utilizando metodología BEM.",
  "CSS Grid": "Creación de diseños avanzados utilizando CSS Grid.",
  "CSS Flexbox": "Construcción de layouts flexibles con Flexbox.",
  "Animaciones CSS y Keyframes": "Creación de animaciones modernas para interfaces de usuario.",
  "JavaScript ES6+": "Desarrollo de aplicaciones modernas utilizando características ES6+.",
  "Promises y Async/Await": "Gestión de operaciones asíncronas en JavaScript.",
  "React.js": "Construcción de interfaces modernas basadas en componentes con React.",
  "React Hooks": "Gestión del estado y lógica reutilizable con React Hooks.",
  "React Router": "Implementación de navegación en aplicaciones React.",
  "Redux Toolkit": "Gestión eficiente del estado global con Redux Toolkit.",
  "TanStack React Query": "Obtención, caché y sincronización eficiente de datos.",
  "React Testing": "Creación de pruebas automatizadas para aplicaciones React.",
  "TypeScript": "Desarrollo de aplicaciones más seguras utilizando tipado estático.",
  "Next.js App Router": "Creación de aplicaciones modernas full-stack con Next.js App Router.",
  "Next.js Server Components": "Uso de componentes servidor para mejorar rendimiento y arquitectura.",
  "Next.js Server Actions": "Implementación de lógica backend segura mediante Server Actions.",
  "Supabase": "Uso de Supabase como backend con base de datos, autenticación y almacenamiento.",
  "PostgreSQL": "Diseño y administración de bases de datos relacionales PostgreSQL.",
  "Arquitectura SaaS": "Diseño de aplicaciones SaaS escalables y preparadas para producción.",
  "Integración OpenAI API": "Integración de modelos de IA y funcionalidades inteligentes en aplicaciones web.",
  "Desarrollo de aplicaciones con IA": "Creación de productos digitales potenciados con inteligencia artificial.",
  "Agentes IA y flujos de trabajo IA": "Construcción de agentes inteligentes y automatización mediante IA.",
  "Ingeniería de prompts": "Diseño de prompts efectivos para optimizar resultados de modelos de IA.",
  "AI-Directed Engineering": "Uso de IA como socio de ingeniería para arquitectura, desarrollo y mejora del flujo de trabajo."
};

export const skillsets = [
  "HTML - Semántico y accesible",
  "Diseño Web Responsivo",
  "JavaScript ES6+",
  "Promises y Async/Await",
  "React.js",
  "React Hooks",
  "React Router",
  "React Context API",
  "Redux Toolkit",
  "TanStack React Query",
  "Pruebas en React",
  "TypeScript",
  "Styled-Components",
  "CSS-in-JS",
  "Tailwind CSS",
  "CSS Grid",
  "CSS Flexbox",
  "Trabajo con APIs (fetch, axios, REST)",
  "Manejo de errores",
  "Git",
  "GitHub Pull Requests y Code Review",
  "Figma",
  "Scrum",
  "Next.js App Router",
  "Next.js Server Components",
  "Next.js Server Actions",
  "Estrategias SSR, SSG, ISR",
  "Despliegue en Vercel",
  "Procesos CI/CD",
  "Supabase",
  "Supabase Authentication",
  "PostgreSQL",
  "Diseño de bases de datos",
  "Row Level Security (RLS)",
  "Autenticación y autorización",
  "Arquitectura SaaS",
  "Arquitectura de aplicaciones en producción",
  "Integración OpenAI API",
  "Desarrollo de aplicaciones con IA",
  "Agentes IA y flujos IA",
  "Ingeniería de prompts",
  "AI-Directed Engineering"
];

export const toLearn = [
  "Pruebas en React",
  "Inteligencia Artificial (IA)",
  "TypeScript Avanzado",
  "Ingeniería de Software AI-Native"
];

export const toLearnDescriptions = {
  "Pruebas en React": "Aprende a crear pruebas automatizadas fiables para componentes y aplicaciones React utilizando prácticas modernas de testing.",
  "Inteligencia Artificial (IA)": "Explora los fundamentos de la IA, modelos de lenguaje, integraciones de IA, agentes y creación de funcionalidades inteligentes para aplicaciones SaaS.",
  "TypeScript Avanzado": "Desarrolla habilidades avanzadas de TypeScript incluyendo tipado, genéricos, utility types y arquitectura escalable.",
  "Ingeniería de Software AI-Native": "Aprende a utilizar la IA como socio de ingeniería para decisiones de arquitectura, desarrollo, revisión de código y creación de aplicaciones profesionales."
};
