export const skillDescriptions = {
  "HTML - Semantyczny i dostępny": "Tworzenie semantycznego i dostępnego HTML zgodnego z nowoczesnymi standardami.",
  "Responsywny Web Design": "Projektowanie interfejsów dopasowanych do różnych urządzeń i ekranów.",
  "Praca zespołowa": "Efektywna współpraca z programistami, projektantami i zespołami produktowymi.",
  "Markdown": "Tworzenie dokumentacji technicznej przy użyciu Markdown.",
  "Niezmienność (Immutability)": "Pisanie przewidywalnego i łatwego w utrzymaniu kodu bez niepożądanych mutacji.",
  "Konwencja BEM w CSS": "Tworzenie skalowalnych arkuszy CSS zgodnie z metodologią BEM.",
  "CSS Grid": "Budowanie zaawansowanych responsywnych układów przy użyciu CSS Grid.",
  "CSS Flexbox": "Tworzenie elastycznych layoutów z wykorzystaniem Flexbox.",
  "Animacje CSS i Keyframes": "Tworzenie płynnych animacji interfejsu użytkownika.",
  "JavaScript ES6+": "Tworzenie nowoczesnych aplikacji z wykorzystaniem funkcji ES6+.",
  "Promises i Async/Await": "Zarządzanie operacjami asynchronicznymi w JavaScript.",
  "React.js": "Budowanie nowoczesnych interfejsów komponentowych w React.",
  "React Hooks": "Zarządzanie stanem i logiką komponentów przy użyciu React Hooks.",
  "React Router": "Implementacja nawigacji w aplikacjach React.",
  "Redux Toolkit": "Efektywne zarządzanie stanem aplikacji przy użyciu Redux Toolkit.",
  "TanStack React Query": "Pobieranie, cache'owanie i synchronizacja danych po stronie klienta.",
  "React Testing": "Pisanie testów automatycznych zapewniających jakość aplikacji React.",
  "TypeScript": "Tworzenie bezpieczniejszego i bardziej skalowalnego kodu dzięki TypeScript.",
  "Next.js App Router": "Budowanie nowoczesnych aplikacji full-stack z wykorzystaniem architektury Next.js App Router.",
  "Next.js Server Components": "Wykorzystanie komponentów serwerowych React dla lepszej wydajności.",
  "Next.js Server Actions": "Tworzenie bezpiecznej logiki backendowej przy użyciu Server Actions.",
  "Supabase": "Wykorzystanie Supabase jako backendu z bazą danych, autoryzacją i storage.",
  "PostgreSQL": "Projektowanie i zarządzanie relacyjnymi bazami danych PostgreSQL.",
  "Architektura SaaS": "Projektowanie skalowalnych aplikacji SaaS zgodnie z zasadami produkcyjnymi.",
  "Integracja OpenAI API": "Dodawanie modeli AI i inteligentnych funkcji do aplikacji webowych.",
  "AI-Directed Engineering": "Wykorzystanie AI jako partnera inżynierskiego w projektowaniu, programowaniu i ulepszaniu procesów pracy.",
  "Desarrollo de aplicaciones con IA": "Creación de aplicaciones inteligentes utilizando tecnologías modernas de inteligencia artificial."
};

export const skillsets = [
  "HTML - Semantyczny i dostępny",
  "Responsywny Web Design",
  "JavaScript ES6+",
  "Promises i Async/Await",
  "React.js",
  "React Hooks",
  "React Router",
  "React Context API",
  "Redux Toolkit",
  "TanStack React Query",
  "Testowanie React",
  "TypeScript",
  "Styled-Components",
  "CSS-in-JS",
  "Tailwind CSS",
  "CSS Grid",
  "CSS Flexbox",
  "Praca z API (fetch, axios, REST)",
  "Obsługa błędów",
  "Git",
  "GitHub Pull Requests i Code Review",
  "Współpraca zespołowa GitHub",
  "Figma",
  "Scrum",
  "Next.js App Router",
  "Next.js Server Components",
  "Next.js Server Actions",
  "Strategie renderowania Next.js",
  "Deployment na Vercel",
  "Procesy CI/CD",
  "Supabase",
  "Supabase Authentication",
  "PostgreSQL",
  "Projektowanie baz danych",
  "Row Level Security (RLS)",
  "Autentykacja i autoryzacja",
  "Architektura SaaS",
  "Architektura aplikacji produkcyjnych",
  "Integracja OpenAI API",
  "Tworzenie aplikacji AI",
  "Agenci AI i workflow AI",
  "Inżynieria promptów",
  "AI-Directed Engineering"
];

export const toLearn = [
  "Testowanie React",
  "Sztuczna inteligencja (AI)",
  "Zaawansowany TypeScript",
  "AI-Native Software Engineering"
];

export const toLearnDescriptions = {
  "Testowanie React": "Nauka tworzenia niezawodnych automatycznych testów dla komponentów i aplikacji React przy użyciu nowoczesnych praktyk testowania.",
  "Sztuczna inteligencja (AI)": "Poznawanie podstaw AI, dużych modeli językowych, integracji AI, agentów oraz tworzenia inteligentnych funkcji w aplikacjach SaaS.",
  "Zaawansowany TypeScript": "Rozwijanie zaawansowanych umiejętności TypeScript, w tym typowania, generyków, utility types i skalowalnej architektury aplikacji.",
  "AI-Native Software Engineering": "Nauka wykorzystania AI jako partnera inżynierskiego w projektowaniu architektury, programowaniu, code review oraz tworzeniu aplikacji produkcyjnych."
};
