export const skillsets = {
  English: [
    "HTML - Semantic & accessible ",
    "Responsive Web design",
    "Teamwork",
    "Markdown",
    "Immutability",
    "CSS BEM convention",
    "CSS Grid",
    "CSS Flexbox",
    "CSS: Animations/Keyframes",
    "React",
    "React Router",
    "Redux-Saga",
    "Redux (Toolkit)",
    "React Hooks",
    "Styled-Components",
    "Error handling",
    "Working with API (fetch, axios)",
    "JavaScript ES6+",
    "Promises, Async/Await",
    "GitHub Pull Requests & Review",
    "Trello",
    "Figma",
    "Scrum",
    "NPM",
    "Git",
  ],
  Polish: [
    "HTML - Semantyczny i dostępny",
    "Responsywny Web design",
    "Praca zespołowa",
    "Markdown",
    "Niezmienność(Immutability)",
    "Konwencja BEM w CSS",
    "CSS Grid",
    "CSS Flexbox",
    "CSS: Animacje/Keyframes",
    "React",
    "React Router",
    "Redux-Saga",
    "Redux (Toolkit)",
    "React Hooks",
    "Styled-Components",
    "Obsługa błędów",
    "Praca z API (fetch, axios)",
    "JavaScript ES6+",
    "Promises, Async/Await",
    "GitHub Pull Requests & Review",
    "Trello",
    "Figma",
    "Scrum",
    "NPM",
    "Git",
  ],
  Spanish: [
    "HTML - Semántico y accesible",
    "Diseño Web Responsivo",
    "Trabajo en equipo",
    "Markdown",
    "Inmutabilidad(Immutability)",
    "Convención BEM en CSS",
    "CSS Grid",
    "CSS Flexbox",
    "CSS: Animaciones/Keyframes",
    "React",
    "React Router",
    "Redux-Saga",
    "Redux (Toolkit)",
    "React Hooks",
    "Styled-Components",
    "Manejo de errores",
    "Trabajar con API (fetch, axios)",
    "JavaScript ES6+",
    "Promises, Async/Await",
    "GitHub Pull Requests & Review",
    "Trello",
    "Figma",
    "Scrum",
    "NPM",
    "Git",
  ],
};

export const toLearn = {
  English: [
    "TypeScript",
    "React Native",
    "React Testing",
    "Next.js",
    "Three.js",
    "Python",
  ],
  Polish: [
    "TypeScript",
    "React Native",
    "Testowanie React",
    "Next.js",
    "Three.js",
    "Python",
  ],
  Spanish: [
    "TypeScript",
    "React Native",
    "Pruebas React",
    "Next.js",
    "Three.js",
    "Python",
  ],
};
