export const skillsets = [
  "HTML - Semantic & accessible ",
  "Responsive Web design",
  "Teamwork",
  "Markdown",
  "Immutability",
  "CSS BEM convention",
  "CSS Grid",
  "CSS Flexbox",
  "CSS: Animations/Keyframes",
  "React",
  "React Router",
  "Redux-Saga",
  "Redux (Toolkit)",
  "React Hooks",
  "Styled-Components",
  "Error handling",
  "Working with API (fetch, axios)",
  "JavaScript ES6+",
  "Promises, Async/Await",
  "GitHub Pull Requests & Review",
  "Trello",
  "Figma",
  "Scrum",
  "NPM",
  "Git",
];

export const toLearn = [
  "TypeScript",
  "React Native",
  "React Testing",
  "Next.js",
  "Three.js",
  "Python",
];
