export const skillsets = {
  English: [
    "HTML - Semantic & accessible",
    "Responsive Web design",
    "Teamwork",
    "Markdown",
    "Immutability",
    "CSS BEM convention",
    "CSS Grid",
    "CSS Flexbox",
    "CSS: Animations/Keyframes",
    "React.js",
    "React Router",
    "Redux (Toolkit)",
    "React Hooks",
    "React Query",
    "React Suspense",
    "Styled-Components",
    "Error handling",
    "Working with API (fetch, axios)",
    "JavaScript ES6+",
    "Promises, Async/Await",
    "GitHub Pull Requests & Review",
    "GitHub Team Collaboration",
    "Trello",
    "Figma",
    "Scrum",
    "NPM",
    "Git",
    "Next.js App Router",
    "Next.js Static Generation & Server-Side Rendering",
    "Next.js API Routes",
    "React Context API",
    "TypeScript",
    "React DevTools",
    "CSS-in-JS",
    "Vercel Deployment",
    "Supabase",
    "Tailwind CSS",
    "Responsive Design with Tailwind CSS",
    "CI/CD for React Apps",
    "JWT Authentication",
    "OAuth2 Integration",
  ],
  Polish: [
    "HTML - Semantyczny i dostępny",
    "Responsywny Web design",
    "Praca zespołowa",
    "Markdown",
    "Niezmienność(Immutability)",
    "Konwencja BEM w CSS",
    "CSS Grid",
    "CSS Flexbox",
    "CSS: Animacje/Keyframes",
    "React",
    "React Router",
    "Redux (Toolkit)",
    "React Hooks",
    "Styled-Components",
    "Obsługa błędów",
    "Praca z API (fetch, axios)",
    "JavaScript ES6+",
    "Promises, Async/Await",
    "GitHub zamawianie Pull Requests & Review",
    "GitHub Współpraca zespołowa",
    "Trello",
    "Figma",
    "Scrum",
    "NPM",
    "Git",
    "Next.js App Router",
    "Next.js Statyczna generacja & Renderowanie po stronie serwera",
    "Next.js API Routes",
    "React Context API",
    "TypeScript",
    "React DevTools",
    "CSS-in-JS",
    "Vercel Deployment",
    "Supabase",
    "Tailwind CSS",
    "Responsywny design z Tailwind CSS",
    "CI/CD dla aplikacji React",
    "JWT Autentykacja",
    "Integracja OAuth2",
  ],
  Spanish: [
    "HTML - Semántico y accesible",
    "Diseño Web Responsivo",
    "Trabajo en equipo",
    "Markdown",
    "Inmutabilidad(Immutability)",
    "Convención BEM en CSS",
    "CSS Grid",
    "CSS Flexbox",
    "CSS: Animaciones/Keyframes",
    "React",
    "React Router",
    "Redux (Toolkit)",
    "React Hooks",
    "Styled-Components",
    "Manejo de errores",
    "Trabajar con API (fetch, axios)",
    "JavaScript ES6+",
    "Promises, Async/Await",
    "GitHub Solicitudes de extracción y revisión",
    "GitHub Colaboración en equipo",
    "Trello",
    "Figma",
    "Scrum",
    "NPM",
    "Git",
    "Next.js App Router",
    "Next.js Generación Estática y Renderizado del Lado del Servidor",
    "Next.js Rutas API",
    "React Context API",
    "TypeScript",
    "React DevTools",
    "CSS-in-JS",
    "Despliegue en Vercel",
    "Supabase",
    "Tailwind CSS",
    "Diseño Responsivo con Tailwind CSS",
    "CI/CD para Apps React",
    "Autenticación JWT",
    "Integración OAuth2",
  ],
};

export const toLearn = {
  English: ["React Testing", "React Native", "Three.js", "Node.js"],
  Polish: ["Testowanie React", "React Native", "Three.js", "Node.js"],
  Spanish: ["Pruebas React", "React Native", "Three.js", "Node.js"],
};
